vim.g.mapleader = " "

require("config_files.options")
require("plugins")
require("plugin_settings.comment")
require("plugin_settings.lsp")
require("plugin_settings.treesitter")
require("plugin_settings.trouble")
require("plugin_settings.which_key")
vim.cmd("source ~/.config/nvim/plugins.vim")
vim.cmd("source ~/.config/nvim/tablemode.vim")
vim.cmd("source ~/.config/nvim/mapping.vim")
require("mappings")
vim.cmd("source ~/.config/nvim/autocmds.vim")
vim.cmd("source ~/.config/nvim/highlights.vim")
