vim.cmd([[hi lualine_a_normal gui=none]])
vim.cmd([[hi lualine_a_select gui=none]])
vim.cmd([[hi lualine_a_visual gui=none]])
vim.cmd([[hi lualine_a_replace gui=none]])
vim.cmd([[hi lualine_a_insert gui=none]])
vim.cmd([[hi NeorgTodoItemOnHoldMark gui=none]])
vim.cmd([[hi NeorgTodoItem1OnHold gui=none guifg=#56b6c2]])
vim.cmd([[hi link NeorgHeading1Title Label]])
vim.cmd([[hi link NeorgHeading1Prefix Label]])
vim.cmd([[hi link NeorgHeading2Title Label]])
vim.cmd([[hi link NeorgHeading2Prefix Label]])
vim.cmd([[hi link NeorgHeading3Title Special]])
vim.cmd([[hi link NeorgHeading3Prefix Special]])
vim.cmd([[hi link NeorgHeading4Title String]])
vim.cmd([[hi link NeorgHeading4Prefix String]])
vim.cmd([[hi link NeorgHeading4Title Label]])
vim.cmd([[hi link NeorgHeading4Prefix Label]])
vim.cmd([[hi link NeorgHeading6Title Label]])
vim.cmd([[hi link NeorgHeading6Prefix Label]])
vim.cmd([[hi link NeorgHeading6Title Special]])
vim.cmd([[hi link NeorgHeading6Prefix Special]])
vim.cmd([[hi CursorLineNr gui=none]])
vim.cmd([[highlight link LspReferenceWrite Visual]])
vim.cmd([[highlight link LspReferenceRead Visual]])
vim.cmd([[highlight link LspReferenceText Visual]])
-- if vim.bo.ft == "startup" then require"startup.utils".set_buf_options() end
